### ISSUE TITLE
Treat nested reviewers list as flat list

### ISSUE THREAD

**Issue by tommilligan** [tommilligan/prowl-github-app#48]
If reviewers are placed in teams using YAML anchor tags, support assigning multiple teams to a target using the syntax:

```yaml
spam:
  - a
  - b

foo:
  - b
  - c

reviewers:
  - *spam
  - *foo
```

This currently gives the illegal internal config
```
reviewers: [
  [
    "a",
    "b"
  ],
  [
    "b",
    "c"
  ]
]
```

but could easily be converted to a flat list
